/**
 * Add Account Page - Multi-step Telegram account creation.
 * Implements Telethon-based login flow:
 * 1. Submit phone number → Backend sends verification code (API credentials selected automatically based on country)
 * 2. Submit verification code → Check if 2FA is needed
 * 3. Submit 2FA password (only if required)
 */
'use client';

import React, { useState, useEffect } from 'react';
import {
  Box,
  Button,
  TextField,
  Typography,
  Alert,
  CircularProgress,
  Paper,
  IconButton,
} from '@mui/material';
import { ArrowBack as ArrowBackIcon } from '@mui/icons-material';
import { useRouter } from 'next/navigation';
import { useTelegramLogin } from '@/hooks/useTelegramLogin';
import { TelegramLoginData } from '@/types';
import { triggerHaptic } from '@/lib/telegram';

export default function AddAccountPage() {
  const router = useRouter();
  const { 
    isLoading, 
    loginState, 
    initiateLogin, 
    submitCode, 
    submitPassword,
    resetLoginState 
  } = useTelegramLogin();
  
  const [activeStep, setActiveStep] = useState(0);
  const [errorMessage, setErrorMessage] = useState<string>('');

  // Simplified form data - no more session_name or platform selection needed
  const [formData, setFormData] = useState<TelegramLoginData & { phone_code: string; password: string }>({
    phone: '',
    session_name: '',  // Auto-generated by backend
    platform: 'android',  // Default, but backend uses country's api_type
    phone_code: '',
    password: '',
  });
  
  const [codeExpiresAt, setCodeExpiresAt] = useState<Date | null>(null);
  const [timeRemaining, setTimeRemaining] = useState<number | null>(null);

  const [errors, setErrors] = useState<Record<string, string>>({});

  // Timer for code expiration
  useEffect(() => {
    if (!codeExpiresAt || activeStep !== 1) {
      setTimeRemaining(null);
      return;
    }

    const interval = setInterval(() => {
      const now = new Date().getTime();
      const expiresAt = codeExpiresAt.getTime();
      const remaining = Math.max(0, Math.floor((expiresAt - now) / 1000));
      
      setTimeRemaining(remaining);
      
      if (remaining === 0) {
        clearInterval(interval);
      }
    }, 1000);

    return () => clearInterval(interval);
  }, [codeExpiresAt, activeStep]);

  const handleChange = (field: string) => (
    event: React.ChangeEvent<HTMLInputElement | HTMLTextAreaElement> | { target: { value: string } }
  ) => {
    setFormData((prev) => ({
      ...prev,
      [field]: event.target.value,
    }));
    // Clear error for this field
    if (errors[field]) {
      setErrors((prev) => ({ ...prev, [field]: '' }));
    }
    // Clear general error message
    if (errorMessage) {
      setErrorMessage('');
    }
  };

  const validateStep = (step: number): boolean => {
    const newErrors: Record<string, string> = {};

    if (step === 0) {
      if (!formData.phone.trim()) {
        newErrors.phone = 'Phone number is required';
      } else {
        const cleanPhone = formData.phone.replace(/\s/g, '');
        // Accept phone with or without + prefix, must have 10-15 digits
        if (!/^\+?\d{10,15}$/.test(cleanPhone)) {
          newErrors.phone = 'Invalid phone number format (e.g., +8801234567890 or 8801234567890)';
        }
      }
    } else if (step === 1) {
      if (!formData.phone_code || !formData.phone_code.trim()) {
        newErrors.phone_code = 'Verification code is required';
      }
    } else if (step === 2) {
      if (!formData.password || !formData.password.trim()) {
        newErrors.password = '2FA password is required';
      }
    }

    setErrors(newErrors);
    return Object.keys(newErrors).length === 0;
  };

  const handlePhoneSubmit = async () => {
    if (!validateStep(0)) {
      triggerHaptic('notification', 'error');
      return;
    }

    setErrorMessage('');

    try {
      const result = await initiateLogin({
        phone: formData.phone,
        session_name: formData.session_name || undefined,
        platform: formData.platform,
      });
      
      if (result.status === 'awaiting_code') {
        // Set code expiration (Telegram codes typically expire in 3-5 minutes)
        const expiresAt = new Date(Date.now() + 3 * 60 * 1000);
        setCodeExpiresAt(expiresAt);
        
        triggerHaptic('selection');
        setActiveStep(1); // Move to verification code step
      } else if (result.status === 'authorized') {
        // Already authorized
        triggerHaptic('notification', 'success');
        router.push('/accounts');
      }
    } catch (error: unknown) {
      // Extract error message from various possible error formats
      let errMsg = 'Failed to send verification code';
      const axiosError = error as { response?: { data?: { detail?: string; error?: string; message?: string } } };
      if (axiosError?.response?.data) {
        const data = axiosError.response.data;
        errMsg = data.detail || data.error || data.message || errMsg;
      } else if (error instanceof Error && error.message) {
        // Handle plain Error objects (from backend error status)
        errMsg = error.message;
      }
      setErrorMessage(errMsg);
      triggerHaptic('notification', 'error');
    }
  };

  const handleCodeSubmit = async () => {
    if (!validateStep(1)) {
      triggerHaptic('notification', 'error');
      return;
    }

    setErrorMessage('');

    try {
      if (!loginState.sessionId) {
        setErrorMessage('Session not found. Please try again.');
        return;
      }
      
      const result = await submitCode(loginState.sessionId, formData.phone_code);
      
      if (result.status === 'awaiting_password') {
        triggerHaptic('selection');
        setActiveStep(2); // Move to 2FA password step
      } else if (result.status === 'authorized') {
        // Success! Account created
        triggerHaptic('notification', 'success');
        router.push('/accounts');
      }
    } catch (error: unknown) {
      // Extract error message from various possible error formats
      let errMsg = 'Verification failed';
      const axiosError = error as { response?: { data?: { detail?: string; error?: string; message?: string } } };
      if (axiosError?.response?.data) {
        const data = axiosError.response.data;
        errMsg = data.detail || data.error || data.message || errMsg;
      } else if (error instanceof Error && error.message) {
        // Handle plain Error objects (from backend error status)
        errMsg = error.message;
      }
      setErrorMessage(errMsg);
      triggerHaptic('notification', 'error');
      
      // If code expired, offer to request a new one
      if (errMsg.toLowerCase().includes('expired')) {
        setFormData(prev => ({ ...prev, phone_code: '' }));
      }
    }
  };

  const handle2FASubmit = async () => {
    if (!validateStep(2)) {
      triggerHaptic('notification', 'error');
      return;
    }

    setErrorMessage('');

    try {
      if (!loginState.sessionId) {
        setErrorMessage('Session not found. Please try again.');
        return;
      }
      
      const result = await submitPassword(loginState.sessionId, formData.password);
      
      if (result.status === 'authorized') {
        // Success!
        triggerHaptic('notification', 'success');
        router.push('/accounts');
      }
    } catch (error: unknown) {
      // Extract error message from various possible error formats
      let errMsg = 'Authentication failed';
      const axiosError = error as { response?: { data?: { detail?: string; error?: string; message?: string } } };
      if (axiosError?.response?.data) {
        const data = axiosError.response.data;
        errMsg = data.detail || data.error || data.message || errMsg;
      } else if (error instanceof Error && error.message) {
        // Handle plain Error objects (from backend error status)
        errMsg = error.message;
      }
      setErrorMessage(errMsg);
      triggerHaptic('notification', 'error');
    }
  };

  const handleRequestNewCode = async () => {
    // Go back to step 0 and request a new code
    setActiveStep(0);
    setErrorMessage('');
    setFormData(prev => ({
      ...prev,
      phone_code: '',
    }));
    setCodeExpiresAt(null);
    setTimeRemaining(null);
    resetLoginState();
    
    // Automatically send new code
    setTimeout(() => {
      handlePhoneSubmit();
    }, 100);
  };

  const handleBack = () => {
    if (activeStep > 0) {
      triggerHaptic('selection');
      setActiveStep((prev) => prev - 1);
      setErrorMessage('');
    } else {
      router.back();
    }
  };

  const renderStepContent = (step: number) => {
    switch (step) {
      case 0:
        return (
          <>
            <Typography variant="h5" component="h1" gutterBottom fontWeight="bold">
              Add Telegram Account
            </Typography>
            <Typography variant="body2" color="text.secondary" mb={3}>
              Enter your phone number to get started.
            </Typography>
            <TextField
              fullWidth
              label="Phone Number"
              value={formData.phone}
              onChange={handleChange('phone')}
              error={!!errors.phone}
              helperText={errors.phone || 'With country code (e.g., +8801234567890)'}
              margin="normal"
              autoFocus
              disabled={isLoading}
              sx={{ mb: 3 }}
            />
          </>
        );

      case 1:
        return (
          <>
            <Typography variant="h5" component="h1" gutterBottom fontWeight="bold">
              Enter Verification Code
            </Typography>
            <Typography variant="body2" color="text.secondary" mb={1}>
              We sent a code to your Telegram app on <strong>{formData.phone}</strong>
            </Typography>
            {timeRemaining !== null && timeRemaining > 0 && (
              <Typography 
                variant="caption" 
                color={timeRemaining < 30 ? 'error' : 'text.secondary'}
                sx={{ mb: 2, display: 'block' }}
              >
                Code expires in {Math.floor(timeRemaining / 60)}:{(timeRemaining % 60).toString().padStart(2, '0')}
              </Typography>
            )}
            {timeRemaining === 0 && (
              <Alert severity="warning" sx={{ mb: 2 }}>
                Code expired. Please request a new code.
              </Alert>
            )}
            <TextField
              fullWidth
              label="Verification Code"
              value={formData.phone_code}
              onChange={handleChange('phone_code')}
              error={!!errors.phone_code}
              helperText={errors.phone_code || '5-digit code from Telegram'}
              margin="normal"
              autoFocus
              disabled={isLoading}
              sx={{ mb: 2 }}
            />
            {(timeRemaining === 0 || (errorMessage && errorMessage.toLowerCase().includes('expired'))) && (
              <Button
                fullWidth
                variant="outlined"
                onClick={handleRequestNewCode}
                disabled={isLoading}
                sx={{ mb: 1 }}
              >
                Request New Code
              </Button>
            )}
          </>
        );

      case 2:
        return (
          <>
            <Typography variant="h5" component="h1" gutterBottom fontWeight="bold">
              Two-Factor Authentication
            </Typography>
            <Typography variant="body2" color="text.secondary" mb={3}>
              Your account has 2FA enabled. Please enter your cloud password to continue.
            </Typography>
            <TextField
              fullWidth
              label="2FA Password"
              type="password"
              value={formData.password}
              onChange={handleChange('password')}
              error={!!errors.password}
              helperText={errors.password || 'Enter your cloud password'}
              margin="normal"
              autoFocus
              disabled={isLoading}
              sx={{ mb: 3 }}
            />
          </>
        );

      default:
        return null;
    }
  };

  const handleNextStep = () => {
    if (activeStep === 0) {
      handlePhoneSubmit();
    } else if (activeStep === 1) {
      handleCodeSubmit();
    } else if (activeStep === 2) {
      handle2FASubmit();
    }
  };

  const getButtonText = () => {
    if (activeStep === 0) return 'Send Code';
    if (activeStep === 1) return 'Verify';
    if (activeStep === 2) return 'Add Account';
    return 'Next';
  };

  return (
    <Box
      sx={{
        minHeight: '100vh',
        display: 'flex',
        flexDirection: 'column',
        bgcolor: 'background.default',
      }}
    >
      {/* Header */}
      <Box
        sx={{
          p: 2,
          display: 'flex',
          alignItems: 'center',
          borderBottom: 1,
          borderColor: 'divider',
        }}
      >
        <IconButton onClick={handleBack} edge="start" disabled={isLoading}>
          <ArrowBackIcon />
        </IconButton>
      </Box>

      {/* Content */}
      <Box
        sx={{
          flex: 1,
          display: 'flex',
          alignItems: 'center',
          justifyContent: 'center',
          p: 3,
        }}
      >
        <Paper
          elevation={0}
          sx={{
            maxWidth: 500,
            width: '100%',
            p: 4,
            border: 1,
            borderColor: 'divider',
          }}
        >
          {errorMessage && (
            <Alert severity="error" sx={{ mb: 3 }}>
              {errorMessage}
            </Alert>
          )}

          {renderStepContent(activeStep)}

          <Button
            fullWidth
            variant="contained"
            size="large"
            onClick={handleNextStep}
            disabled={isLoading}
            sx={{ mt: 2, minHeight: 48 }}
          >
            {isLoading ? (
              <Box sx={{ display: 'flex', alignItems: 'center', gap: 1 }}>
                <CircularProgress size={20} color="inherit" />
                <Typography variant="button">Processing...</Typography>
              </Box>
            ) : (
              getButtonText()
            )}
          </Button>
        </Paper>
      </Box>
    </Box>
  );
}
